### PR TITLE
add features and limitations to docs

### PR DESCRIPTION
**Pull request by lachie83**

### CODE REVIEW

**Comment by rbitia** [comment]
By Kubernetes pod spec do you mean their configuration?

**Comment by lachie83** [comment]
> By Kubernetes pod spec do you mean their configuration?

Correct. The Kubernetes manifest.

**Comment by rbitia** [comment]
As long as that's a widely used naming convention it looks good - but maybe saying Kubernetes pod configuration would make more sense?

**Comment by lachie83** [comment]
Thanks for the review. I agree and will update before we merge.

**Comment by lachie83** [comment]
@rbitia I've addressed based on your feedback. Can you take another pass at review?

**Comment by rbitia** [comment]
looks good :D

**Pull request merged**
